name: Combined Workflow

on:
  workflow_dispatch:

jobs:
  download_and_store_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30
          pip install pandas

      - name: Download Nifty50 Data
        run: |
          python3 scripts/download_nifty50_data.py

      - name: Store CSV data to SQLite DB
        run: |
          python3 scripts/store_csv_to_db.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add temp_csv/*.csv nifty50_data_v1.db
          git commit -m "Download Nifty50 data, store to DB, and update CSVs"
          git push origin main

  predict_rnn:
    runs-on: ubuntu-latest
    needs: download_and_store_csv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predict_rnn.py
        run: |
          python predict_rnn.py

      - name: Check if predictions.db exists
        run: |
          if [ -f "predictions/predictions.db" ]; then
            echo "Prediction database found."
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add predictions/predictions.db
            git commit -m "Update prediction database"
            git push
          else
            echo "No predictions.db file found, skipping commit"
          fi
