name: Combined Workflow

on:
  schedule:
    # Schedule for download_nifty50_data.py and store_csv_to_db.py (every 5 mins from 9:16 AM to 3:31 PM IST)
    - cron: "16-59/5 3 * * 1-5" # 9:16 AM to 9:59 AM IST
    - cron: "0-59/5 4-8 * * 1-5"  # 10:00 AM to 2:59 PM IST
    - cron: "0-31/5 9 * * 1-5"   # 3:00 PM to 3:31 PM IST
    # Schedule for train_rnn.py (10:00 PM IST)
    - cron: "30 16 * * 1-5"       # 10:00 PM IST
    # Schedule for predict_rnn.py (every 5 mins from 9:18 AM to 3:33 PM IST)
    - cron: "18-59/5 3 * * 1-5" # 9:18 AM to 9:59 AM IST
    - cron: "0-59/5 4-8 * * 1-5"  # 10:00 AM to 2:59 PM IST
    - cron: "0-33/5 9 * * 1-5"   # 3:00 PM to 3:33 PM IST
  workflow_dispatch:

jobs:
  download_and_store:
    if: "(github.event.schedule == '16-59/5 3 * * 1-5' || github.event.schedule == '0-59/5 4-8 * * 1-5' || github.event.schedule == '0-31/5 9 * * 1-5')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30 pandas

      - name: Download Nifty50 Data
        run: |
          python download_nifty50_data.py

      - name: Store CSV to Database
        run: |
          python store_csv_to_db.py

  train:
    if: "github.event.schedule == '30 16 * * 1-5'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train RNN Model
        run: |
          mkdir -p models
          python train_rnn.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/
          git commit -m "Add trained models and scalers"
          git push

  predict:
    if: "(github.event.schedule == '18-59/5 3 * * 1-5' || github.event.schedule == '0-59/5 4-8 * * 1-5' || github.event.schedule == '0-33/5 9 * * 1-5')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Prediction
        run: |
          python predict_rnn.py

      - name: Check and Commit Predictions
        run: |
          if [ -f "predictions/predictions.db" ]; then
            echo "Prediction database found."
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add predictions/predictions.db
            git commit -m "Update prediction database"
            git push
          else
            echo "No predictions.db file found, skipping commit."
